### ISSUE TITLE
Why you don't use base64 encoding?

### ISSUE THREAD

**Issue by denisx** [souporserious/restyle#11]
Why you don't use base64 encoding? at `function hash(str: string): string {` place
It can make css classnames less length

For example, [webpack/loader-utils](https://github.com/webpack/loader-utils) has utils at different hash funcs and bases

**Comment by souporserious** [comment]
I'm open to another hashing function, especially if it's smaller output and wouldn't clash. This was just the first go at getting something working 😄 happy to accept a PR if you have something in mind.

**Comment by souporserious** [comment]
Closing this as the current encoding works, if there's a better method I'm happy to take a look at a PR.
