### ISSUE TITLE
Styled function props not recognized by TypeScript

### ISSUE THREAD

**Issue by StephenTHendrix** [souporserious/restyle#13]
This example from the docs:

<img width="789" alt="Screenshot 2024-08-12 at 1 56 35 PM" src="https://github.com/user-attachments/assets/8b3d5963-a3a0-4a37-9d70-af30ee52269d">

Throws a type error:

```
Type '{ children: Element[]; gridTemplateColumns: string; }' is not assignable to type 'IntrinsicAttributes & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & { ...; }'.
  Property 'gridTemplateColumns' does not exist on type 'IntrinsicAttributes & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & { ...; }'.ts(2322)
(property) gridTemplateColumns: string
```

PS though overall I'm loving this library! I'm using it with Next; being able to use the library with server-side components and not needing a weird global config in the root layout is awesome 🙏

**Comment by StephenTHendrix** [comment]
Wow never mind I guess; looks like I maybe just needed to restart the TS server 🙈

**Comment by souporserious** [comment]
Yeah, I ran into this too! Thank you for filing an issue in case others do as well 🙏
