### ISSUE TITLE
feature request: support for variants

### ISSUE THREAD

**Issue by nikitatrifan** [souporserious/restyle#16]
Hey. I really like this library- I think it has the potential to reach industry wide adoption.

I was looking at it from the standpoint of an interface library developer and thought it'd be nice to support variants out of the box. One of the best features that the [stitches](https://stitches.dev/docs/variants) team ever shipped imo.

If you're curious, here's how the variants can scale if you wanted to use this approach to outline all variants for a button. Pretty clean when coupled with variables. [See here](https://github.com/sashimi36/junoblocks/blob/5f689facad6592bccf9e7c7d1b9843407184058f/src/components/Button/Button.tsx#L68)

Would be interested to hear what you think.

Just an idea too- in theory this would be met with great interest on product hunt if it hasn't been posted there yet.

Peace ✌🏻

**Comment by souporserious** [comment]
Hey @nikitatrifan appreciate the kind words! I'm trying to keep some of the utilities to only what is necessary if there isn't another pattern for it so I don't want to add a dedicated variants feature as of right now.

With that, I added a [variants example](https://github.com/souporserious/restyle?tab=readme-ov-file#variants) to showcase how to achieve this with style props which is relatively straightforward:

```tsx
import { styled, type CSSObject } from 'restyle'

type AlertVariant = 'note' | 'success' | 'warning'

const variantStyles = {
  note: {
    backgroundColor: '#1b487d',
    borderLeftColor: '#82aaff',
  },
  success: {
    backgroundColor: '#2b7b3d',
    borderLeftColor: '#5bc873',
  },
  warning: {
    backgroundColor: '#b36b00',
    borderLeftColor: '#ffb830',
  },
} satisfies Record<AlertVariant, CSSObject>

export const Alert = styled('div', (props: { variant: AlertVariant }) => {
  return {
    padding: '1.5rem 2rem',
    borderRadius: '0.5rem',
    color: 'white',
    ...variantStyles[props.variant],
  }
})
```

Never thought about posting this on Product Hunt 😄 might be a nice to do once React 19 is stable.

**Comment by nikitatrifan** [comment]
@souporserious that's so cool thanks! Is it generated on every render? Just trying to think, won't be so cool if that button re-renders its css all the time if it's in a virtualized table with thousands of rows

**Comment by souporserious** [comment]
If it's used in a Client Component, yes it will be called each render. It's more optimized when used in a Server Component right now. I wouldn't recommend using these sort of components in a data table since it's still experimental in React. But it would be interesting to explore memoization in these cases since the function is simply a template.

In the future, if I add a first-class variants API it most likely would overload the `styled` function so you can provide the templated prop styles similar to this:

```tsx
import { styled } from 'restyle'

export const Alert = styled('div', {
  padding: '1.5rem 2rem',
  borderRadius: '0.5rem',
  color: 'white',
  backgroundColor: {
    variant: {
      note: '#1b487d',
      success: '#2b7b3d',
      warning: '#b36b00',
    },
  },
  borderLeftColor: {
    variant: {
      note: '#82aaff',
      success: '#5bc873',
      warning: '#ffb830',
    },
  },
})
```

**Comment by nikitatrifan** [comment]
@souporserious looks clean, I like it! 

If I remember it right, with stitches you get typescript autocomplete for variants.

```tsx
// fully typed so this errors
<Alert variant="error" />
```

Idk if it's overkilling it but compound variables is a thing nevertheless:

```ts
compoundVariants: [
  {
    // it is a variant called "variant"
    variant: 'primary',
    // a variant can be a boolean value etc
    disabled: true,
    // matching combination will have these styles applied
    css: {
      $$backgroundColor: '$colors$dark30',
      $$textColor: '$colors$light95',
      $$iconColor: '$iconColors$disabled'
    }
  },
  ... // disabled states for all the other variants
]
```

I think you're right it will likely overload the styled function, maybe there's a better way to plug them together. 

```ts
Alert.createCompoundVariant({ variant: 'note', kind: 'toast' }, { ... })
```

This obviously adds complexity; back then this 10x my workflow and I never needed to truly focus on what's going on in a given component if I wanted to quickly tweak a variant or two, or their global styles. It was seamless like this. I don't remember if this was a css issue exactly, but there might have been some inheritance problems. Very likely that was out of the library's scope though.

**Comment by nikitatrifan** [comment]
Hey I just hacked this together really quickly. What do you think: https://gist.github.com/nikitatrifan/8aaa3054c0355ffe0c173d22991d5e4a
