### ISSUE TITLE
Support for non DOM components

### ISSUE THREAD

**Issue by mkatrenik** [souporserious/restyle#20]
Hi, great lib! 
I wanted to use it's `css` prop with higher level UI toolkit like Mantine, which means adding `css` on react components which are not DOM nodes. 
Logic in create-restyle-props.ts was not suitable for this, also i had issue with components passing refs to children and components assuming there is always just 1 child. So my solution to this is [here](https://github.com/saunos/restyle-components/blob/main/src/forward-ref-wrapper.ts) - basically i'm wrapping component and it's styles to ref forwarding component. 

<img width="270" alt="Screenshot 2024-11-10 at 16 08 14" src="https://github.com/user-attachments/assets/0b972315-d5e4-4e96-b53d-287f49b696a2">

I've had no issues so far - i would be happy if restyle directly supported non dom components. wdyt?

**Comment by souporserious** [comment]
I originally had this behavior, but then reverted it because it was unpredictable if the component actually accepted a `className`. My suggestion would be to use the `styled` function which gives you access to the `css` prop and ensures the wrapped component accepts a `className` prop:

```tsx
import { styled } from 'restyle'
import Link from 'next/link'

const StyledLink = styled(Link)

export default App() {
  return <StyledLink css={{ ':visited': 'tomato' }}>...</StyledLink>
}
```
