### ISSUE TITLE
Are keyframes planned or supported?

### ISSUE THREAD

**Issue by zaydek** [souporserious/restyle#8]
Hi. this is an interesting library. Thanks for making it. I'm wondering if keyframes are planned and or already supported? Thanks.

**Comment by souporserious** [comment]
Keyframes are not currently supported. I started working on a `GlobalStyles` component [here](https://github.com/souporserious/restyle/tree/add-global-styles) that will help with this feature though. I've been prioritizing getting the core library stable first, then will take a look at both of these. For now, you can define keyframes in a CSS file and reference them using the `css` or `styled` functions.

**Comment by zaydek** [comment]
Thanks much appreciated.
